table 'pagos de pedidos'
	lineageTag: 8de090bf-a0eb-4127-becc-ad8cc03309a8

	measure 'Sales by Payment Type' =
			
			CALCULATE(
			    SUM('Resumen de Ventas'[price]),
			    TREATAS(VALUES('pagos de pedidos'[order_id]), 'ID ordenes'[order_id])
			)
		lineageTag: 32874fb9-183c-48d2-ae71-1f5a6155d3ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order_id
		dataType: string
		lineageTag: 249e32bf-83ae-40ce-bce2-0ea8e338e0dd
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_sequential
		dataType: int64
		formatString: 0
		lineageTag: f749424a-91dc-43c6-b317-aac35d1e71dc
		summarizeBy: sum
		sourceColumn: payment_sequential

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: 46cf071d-1771-487f-960b-b51bcda90ffc
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_installments
		dataType: int64
		formatString: 0
		lineageTag: 7caf0f7d-9f69-49d6-8f6e-aae9e4670f53
		summarizeBy: sum
		sourceColumn: payment_installments

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: double
		lineageTag: bbde038b-a9a4-4c27-a43b-730909770df4
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'pagos de pedidos' = m
		mode: import
		source =
				let
				    Origen = PostgreSQL.Database("localhost", "olist_analytics"),
				    public_order_payments = Origen{[Schema="public",Item="order_payments"]}[Data]
				in
				    public_order_payments

