table 'Resumen de Ventas'
	lineageTag: edfadd81-3842-47e5-834c-141a5a566b1a

	measure 'Order Count' = DISTINCTCOUNT('Resumen de Ventas'[order_id])
		formatString: 0
		lineageTag: 29d717f3-4b61-4969-a33c-989479313e4a

	measure Average_Unit_Price =
			
			DIVIDE('Finanzas y Cuotas'[Total Sales], [Order Count], 0)
		lineageTag: f1d9a4d2-8375-41f9-8077-0906e274d9a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variación % Mes Anterior' =
			
			VAR _mesActual =
			    SELECTEDVALUE('Resumen de Ventas'[Mes Numero])
			VAR _ventasActual = 'Finanzas y Cuotas'[Total Sales]
			VAR _ventasAnterior =
			    CALCULATE(
			        'Finanzas y Cuotas'[Total Sales],
			        FILTER(
			            ALL('Resumen de Ventas'),
			            MONTH('Resumen de Ventas'[order_date]) = _mesActual - 1
			        )
			    )
			RETURN
			    IF(
			        NOT ISBLANK(_ventasAnterior) && _ventasAnterior <> 0,
			        DIVIDE(_ventasActual - _ventasAnterior, _ventasAnterior),
			        BLANK()
			    )
		lineageTag: c30e507e-757c-4605-9d79-ae5b8330d62c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order_id
		dataType: string
		lineageTag: 96f39393-c7cc-4a76-8225-ffc3f1e22b71
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 0413abbb-b69e-44b1-b543-edd6b851a3b0
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b58488d4-63a7-4f72-a035-9d8a763e02ee
		summarizeBy: none
		sourceColumn: order_date

		variation Variación
			isDefault
			relationship: e8a0fefb-f5f0-4797-8c49-0958e34ac25c
			defaultHierarchy: LocalDateTable_c09359a1-16f1-4877-8e4c-d78aa3b9851c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column category_name
		dataType: string
		lineageTag: 2989de8c-1f3b-46b6-a072-bb2c1c9519e4
		summarizeBy: none
		sourceColumn: category_name

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 1a0593d7-f7b3-4629-9900-db81b239d0df
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column freight_value
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 965eb690-2586-4786-b1fc-9612db223363
		summarizeBy: sum
		sourceColumn: freight_value

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 85738858-f706-48f0-a6f4-32d20e0c5434
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: customer_state

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column seller_state
		dataType: string
		lineageTag: 74a91e10-4d07-4e63-8158-e6d6ce15ce8b
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: seller_state

		annotation SummarizationSetBy = Automatic

	column 'Día Numero' = WEEKDAY([order_date],1)
		formatString: 0
		lineageTag: 40b5ea36-6445-4968-af4b-17bd82d43df5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Día Nombre' = SWITCH([Día Numero],1,"Domingo",2,"Lunes",3,"Martes",4,"Miercoles",5,"Jueves",6,"Viernes",7,"Sábado")
		lineageTag: 786e5cd5-748f-4ce9-b401-59e6ea777c6c
		summarizeBy: none
		sortByColumn: 'Día Numero'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Mes Numero' = MONTH('Resumen de Ventas'[order_date])
		formatString: 0
		lineageTag: 9f30d570-d7d2-4cac-ad10-c6f8298e4da7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Mes Nombre' =
			
			SWITCH(
			    MONTH('Resumen de Ventas'[order_date]),
			    1, "Enero",    2, "Febrero",  3, "Marzo",
			    4, "Abril",    5, "Mayo",     6, "Junio",
			    7, "Julio",    8, "Agosto",   9, "Septiembre",
			    10, "Octubre", 11, "Noviembre", 12, "Diciembre"
			)
		lineageTag: e6a9927b-7858-4af6-a59d-16bdf392de4a
		summarizeBy: none
		sortByColumn: 'Mes Numero'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Resumen de Ventas' = m
		mode: import
		source =
				let
				    Origen = PostgreSQL.Database("localhost", "olist_analytics"),
				    public_v_order_summary = Origen{[Schema="public",Item="v_order_summary"]}[Data],
				    #"Valor reemplazado" = Table.ReplaceValue(public_v_order_summary,"_"," ",Replacer.ReplaceText,{"category_name"}),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Valor reemplazado",{{"category_name", Text.Proper, type text}})
				in
				    #"Poner En Mayúsculas Cada Palabra"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

