table 'Resumen de Ventas'
	lineageTag: edfadd81-3842-47e5-834c-141a5a566b1a

	measure 'Total Sales' = SUM('Resumen de Ventas'[price])
		lineageTag: 84dde880-5eed-4caa-ac23-915e31691ccc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Order Count' = DISTINCTCOUNT('Resumen de Ventas'[order_id])
		formatString: 0
		lineageTag: 29d717f3-4b61-4969-a33c-989479313e4a

	measure 'Avg Ticket' = DIVIDE([Total Sales], [Order Count])
		lineageTag: f2a4d2c9-97bd-48fa-8621-aa44bcc0b9a2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'total mismo mes del año anterior' = CALCULATE([Total Sales], DATEADD('Resumen de Ventas'[order_date].[Date], -1, YEAR))
		lineageTag: aeb0d96c-c83c-46a8-a2b2-453dcf90688e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order_id
		dataType: string
		lineageTag: 96f39393-c7cc-4a76-8225-ffc3f1e22b71
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 0413abbb-b69e-44b1-b543-edd6b851a3b0
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b58488d4-63a7-4f72-a035-9d8a763e02ee
		summarizeBy: none
		sourceColumn: order_date

		variation Variación
			isDefault
			relationship: e8a0fefb-f5f0-4797-8c49-0958e34ac25c
			defaultHierarchy: LocalDateTable_c09359a1-16f1-4877-8e4c-d78aa3b9851c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column category_name
		dataType: string
		lineageTag: 2989de8c-1f3b-46b6-a072-bb2c1c9519e4
		summarizeBy: none
		sourceColumn: category_name

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 1a0593d7-f7b3-4629-9900-db81b239d0df
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column freight_value
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 965eb690-2586-4786-b1fc-9612db223363
		summarizeBy: sum
		sourceColumn: freight_value

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 85738858-f706-48f0-a6f4-32d20e0c5434
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: customer_state

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column seller_state
		dataType: string
		lineageTag: 74a91e10-4d07-4e63-8158-e6d6ce15ce8b
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: seller_state

		annotation SummarizationSetBy = Automatic

	column 'Día de semana #' = WEEKDAY([order_date],1)
		formatString: 0
		lineageTag: 40b5ea36-6445-4968-af4b-17bd82d43df5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Día de la semana texto' = SWITCH([Día de semana #],1,"Domingo",2,"Lunes",3,"Martes",4,"Miercoles",5,"Jueves",6,"Viernes",7,"Sábado")
		lineageTag: 786e5cd5-748f-4ce9-b401-59e6ea777c6c
		summarizeBy: none
		sortByColumn: 'Día de semana #'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Resumen de Ventas' = m
		mode: import
		source =
				let
				    Origen = PostgreSQL.Database("localhost", "olist_analytics"),
				    public_v_order_summary = Origen{[Schema="public",Item="v_order_summary"]}[Data],
				    #"Valor reemplazado" = Table.ReplaceValue(public_v_order_summary,"_"," ",Replacer.ReplaceText,{"category_name"}),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Valor reemplazado",{{"category_name", Text.Proper, type text}})
				in
				    #"Poner En Mayúsculas Cada Palabra"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

