table 'Ubicaciones por Ciudad'
	lineageTag: cc879205-8faa-4798-9b54-03cf544bc746

	column zip_code_id
		dataType: int64
		formatString: 0
		lineageTag: 26a4f8f9-837a-40a6-803d-83c679ca4c25
		summarizeBy: none
		sourceColumn: zip_code_id

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 3332a481-cd2c-439e-92ef-826a29a14d1b
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 98a24dbd-b0b1-4257-9bb2-68359d8277fb
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column city
		dataType: string
		lineageTag: bea7eae8-879f-468f-8067-45ebce3c0035
		dataCategory: City
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 56afe528-4032-4039-8710-358e199ccdb8
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	partition 'Ubicaciones por Ciudad' = m
		mode: import
		source =
				let
				    Origen = PostgreSQL.Database("localhost", "olist_analytics"),
				    public_v_clean_geolocation_enriched = Origen{[Schema="public",Item="v_clean_geolocation_enriched"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(public_v_clean_geolocation_enriched, each [zip_code_id] <> 95130 and [zip_code_id] <> 68379 and [zip_code_id] <> 78131 and [zip_code_id] <> 18243 and [zip_code_id] <> 57319 and [zip_code_id] <> 53990 and [zip_code_id] <> 45983 and [zip_code_id] <> 58441)
				in
				    #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

